site_name: fuzzy-couscous
theme:
  name: material
  palette:
    - scheme: default
      primary: 'indigo'
      accent: 'indigo'
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    - scheme: slate
      primary: 'indigo'
      accent: 'indigo'
      toggle:
        icon: material/weather-night
        name: Switch to light mode

plugins:
  - include-markdown
  - search

nav:
  - index.md
  - usage.md
  - tips.md
  - documentation.md
  - deployment.md
  - Code of Conduct: codeofconduct.md
  - license.md
  - Changelog: https://github.com/Tobi-De/fuzzy-couscous/releases

markdown_extensions:
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.tabbed
  - attr_list
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.highlight:
      linenums: true
  - pymdownx.superfences
  - pymdownx.details
  - admonition
  - toc:
      baselevel: 2
      permalink: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
  - meta
  - pymdownx.tasklist:
      custom_checkbox: true

extra:
  social:
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/tobidegnon
      name: Tweet
    - icon: fontawesome/brands/github
      link: https://github.com/Tobi-De/fuzzy-couscous
      name: Github
    - icon: material/email
      link: "mailto:tobidegnon@proton.me"
